base_model: NousResearch/Meta-Llama-3-8B-Instruct
experts:
  - source_model: Sao10K/L3-8B-Lunaris-v1
    positive_prompts:
    - "tell me"
    - "describe"
    - "assistant"
    - "explain"

  - source_model: Sao10K/L3-8B-Stheno-v3.2
    positive_prompts:
    - "erotica"
    - "sexuality"
    - "intimacy"
    - "aphrodisiac"
    - "kissing"
    - "cuddling"
    - "caressing"
    - "touching"
    - "fondling"
    - "masturbation"
    - "orgasm"
    - "climax"
    - "penetration"
    - "insertion"
    - "withdrawal"
    - "ejaculation"
    - "semen"
    - "sperm"
    - "vulva"
    - "vagina"
    - "cunt"
    - "pussy"
    - "labia"
    - "clitoris"
    - "clitoral"
    - "nipples"
    - "areola"
    - "breasts"
    - "boobs"
    - "tits"
    - "titty"
    - "anal"
    - "anus"
    - "rectum"
    - "butt"
    - "rear"
    - "ass"
    - "backdoor"
    - "cock"
    - "dick"
    - "penis"
    - "shaft"
    - "glans"
    - "foreskin"
    - "testicles"
    - "balls"
    - "scrotum"
    - "oral"
    - "blowjob"
    - "fellatio"
    - "sucking"
    - "swallowing"
    - "cunnilingus"
    - "tongue"
    - "licking"
    - "fingering"
    - "prostate"
    - "g-spot"
    - "arousal"
    - "desire"
    - "libido"
    - "passion"
    - "lust"
    - "sexual"
    - "intimate"
    - "explicit"
    - "graphic"
    - "lewd"
    - "obscene"
    - "vulgar"
    - "dirty"
    - "filthy"
    - "raunchy"
    - "xxx"
    - "adult"
    - "mature"
    - "pornographic"
    - "threesome"
    - "gangbang"
    - "bisexuality"
    - "homosexuality"
    - "heterosexuality"
    - "lesbians"
    - "gay"
    - "bisexual"
    - "shemale"
    - "transgender"
    - "shemale sex"
    - "transvestite"
    - "crossdressing"
    - "panties"
    - "panty"
    - "bra"
    - "breastfeeding"
    - "lactation"
    - "titfuck"
    - "teasing"
    - "seduction"
    - "foreplay"
    - "afterglow"
    - "lovemaking"
    - "sex toys"
    - "vibrator"
    - "dildo"
    - "anal beads"
    - "butt plug"
    - "prostate massager"
    - "cock ring"
    - "cunnilingus"
    - "anilingus"
    - "fisting"
    - "deep throat"
    - "choking"
    - "facefucking"
    - "gagging"
    - "spanking"
    - "whipping"
    - "bdsd"
    - "sm"
    - "sadism"
    - "masochism"
    - "dominance"
    - "submission"
    - "fetishes"
    - "bondage"
    - "roleplay"
    - "cosplay"
    - "fantasy"
    - "kinky"
    - "taboo"
    - "exhibitionism"
    - "voyeurism"
    - "masturbation cream"
    - "condom"
    - "lubricant"
    - "pregnancy"
    - "nipples piercing"
    - "genital piercing"
    - "sex position"
    - "kama sutra"
    - "orgasm denial"
    - "sensual massage"
    - "erotic massage"
    - "sex games"
    - "strip tease"
    - "burlesque"
    - "pole dancing"
    - "sex ed"
    - "sex therapy"

  - source_model: Sao10K/L3-8B-Niitama-v1
    positive_prompts:
    - "love"
    - "shy"
    - "story"
    - "blush"
  - source_model: nothingiisreal/L3-8B-Celeste-V1.2
    positive_prompts:
    - "develop"
    - "care"
    - "sudden"
    - "suddenly"
    - "but"
tokenizer_source: union
